#ifndef __TILES_H__
#define __TILES_H__

#include "raylib.h"

typedef enum tile_type_e
{
  // Row 1
  TILE_GROUND,
  TILE_GRASS_LEFT,
  TILE_GRASS_MIDDLE,
  TILE_GRASS_RIGHT,
  TILE_HILL_LEFT,
  TILE_HILL_MIDDLE_LEFT,
  TILE_HILL_MIDDLE,
  TILE_HILL_MIDDLE_RIGHT,
  TILE_HILL_RIGHT,
  TILE_HILL_TOP,
  // Row 2
  TILE_BRICK,
  TILE_QUE_BLOCK,
  TILE_WARP_PIPE_TOP_LEFT,
  TILE_WARP_PIPE_TOP_RIGHT,
  TILE_WARP_PIPE_BOTTOM_LEFT,
  TILE_WARP_PIPE_BOTTOM_RIGHT,
  TILE_BRICK_NICE,
  TILE_CLOUD_BOTTOM_LEFT,
  TILE_CLOUD_BOTTOM_MIDDLE,
  TILE_CLOUD_BOTTOM_RIGHT,
  // Row 3
  TILE_CLOUD_TOP_LEFT,
  TILE_CLOUD_TOP_MIDDLE,
  TILE_CLOUD_TOP_RIGHT,
  TILE_DOOR_TOP,
  TILE_DOOR_BOTTOM,
  TILE_HOUSE_TOP,
  TILE_HOUSE_MIDDLE,
  TILE_WINDOW_RIGHT,
  TILE_WINDOW_LEFT,
  TILE_FLAG_POLE,
  // Row 4
  TILE_FLAG_LEFT,
  TILE_FLAG_MIDDLE,
  TILE_FLAG_TOP,

  TILE_NUM_TYPES
} tile_type_e;

#endif